//#include <stdlib.h>
#include <cstdlib>
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <exception>
#include <stdexcept>
#include <locale>
#include <algorithm>
#include <exception>